import type { Metadata } from "next";

import { Poppins } from "next/font/google";

import "../globals.css";
import { Background, Container } from "@/components";
import { NavbarHome } from "@/components/ui/navbar";

const poppins = Poppins({
  weight: ["300", "400", "500", "600", "700", "800", "900"],
  style: ["normal", "italic"],
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.className} flex flex-col min-h-screen overflow-x-hidden`}>
        <Background src="/images/apples-nuts.webp" alt="home background" className="justify-between h-full min-h-screen pb-12 bg-dark/40">
          <div className="bg-light">
            <NavbarHome />
          </div>
          <Container>{children}</Container>
        </Background>
      </body>
    </html>
  );
}
